SRC += 	visual_setup.c \
	tools.c \
	solve.c \
	show_stats.c \
	print.c \
	path_quantity_estimate.c \
	new_algo_function_content.c \
	new_algo.c \
	main.c \
	louis_tools.c \
	louis_search.c \
	louis_save_path.c \
	louis_room_sort.c \
	louis_room_check.c \
	louis_data.c \
	louis_alg.c \
	link_data.c \
	init_rooms.c \
	init_parsing.c \
	init_links.c \
	init_data.c \
	init_checking.c \
	init.c \
	hashtable.c \
	hash_tools.c \
	graph_simplifier.c \
	get_param.c \
	display_spe_cases.c \
	display_result.c \
	data.c \
	creat_position.c \
	buffer_function.c \
	ants.c \
	algo_tools_2.c \
	algo_tools.c \
	algo_paths_tools.c 
