PAT += 	srcs/visual_setup.c \
	srcs/tools.c \
	srcs/solve.c \
	srcs/show_stats.c \
	srcs/print.c \
	srcs/path_quantity_estimate.c \
	srcs/new_algo_function_content.c \
	srcs/new_algo.c \
	srcs/main.c \
	srcs/louis_tools.c \
	srcs/louis_search.c \
	srcs/louis_save_path.c \
	srcs/louis_room_sort.c \
	srcs/louis_room_check.c \
	srcs/louis_data.c \
	srcs/louis_alg.c \
	srcs/link_data.c \
	srcs/init_rooms.c \
	srcs/init_parsing.c \
	srcs/init_links.c \
	srcs/init_data.c \
	srcs/init_checking.c \
	srcs/init.c \
	srcs/hashtable.c \
	srcs/hash_tools.c \
	srcs/graph_simplifier.c \
	srcs/get_param.c \
	srcs/display_spe_cases.c \
	srcs/display_result.c \
	srcs/data.c \
	srcs/creat_position.c \
	srcs/buffer_function.c \
	srcs/ants.c \
	srcs/algo_tools_2.c \
	srcs/algo_tools.c \
	srcs/algo_paths_tools.c 
